language: node_js
node_js:
- '9'
- stable
before_script:
- git config --global user.email "jim.zhan@me.com"
- git config --global user.name "jimzhan"
- git remote rm origin
- git remote add origin https://jimzhan:${GH_TOKEN}@github.com/jimzhan/create-esnext-app.git
after_success: npm run release -- --no-verify
env:
  global:
    secure: TtyzLpIFyE0BrRA8bCzN0UrqTow4aQWqbX2Wdtm0Rg8INH7ddtMoZnR2JH8FcaFtzR5eVSo4V2H8dBo1j8ktEZVRDGyoJPow1dBJ3wSPj1vxv88oDHi5r8NMrgV3qVsf8io78oJw52o9LiWOAiuyjS6bOksXvwpoekeHXFrpkd9GJWMG9p7Y//fdzso3pZUNG8BLZCGpguAT83UABxq2JfgdXAWQvOexHW00j3Jgi3QnmT00nFnGdaT89f9sh4zKLBiMf7W7hSZqiCMY0/l04RoLUapVw7JwOOVN0xnZnHGfyhV9DNNWTa9IlwxUMa0avuwAlI/i5XY+fvhKqTLwFieB/to1nYyqzBck47II/kCik+6Jo6NN2nN4gOWGra+5/O6pxdU1l5UDMkPFEBE0HaCAUVtGUdQ6585JNfFR7HZP0ot4HrPSMLRwFACPtP/ySp+brN4HtLQFworucLBTvyUTlbnaPfp1vdH7FFxpTsTRlcfnaaaE1ES+j/4ClX4ViFmrrIs8DpQv4tv12r+5pmpITNZplU3y2FU6cvhVN/t9fj7ARjHPbYim/KyYkx57ipBu4CQoIvfUXH/ANmWajoDR3rQtmGGIj352IPwrlDEYVM81ffJlyXmAlt8HPMajbxy3EH/krQDgsvWIGh3SbggLu8V9hOhkjP1KUp7OhhQ=
deploy:
  provider: npm
  email: jim.zhan@me.com
  api_key:
    secure: PpKxCr80W6vGgnMcISoFMtXLf392NKVSdEhsWmwhYzHoGpnb25Y86yFSyGiur3wxwYdPiSwbdP7BYO1XfwkrkHx8u4sI2Rin279Mn25mCenJCKfze3eqcjIDiST3ilHVCHJMJByKHRc/XaMaF66vXs65IJPKKQuUpQECiHvSw5Ywx8uj+sdIsaT5ep0zRQs9YNwc4/u4IiRA6w02ds5v/5pgF3oX+iI2k1ClqBBFs7AcpeOT7IjJUpCx73So1FEAoXdFWdRu59lO5FCGFIxlbGgZpDeE3po95XJ14KdcFvaYoRj3XxHwU4RT2sUBVnButIf5MSZWdW/+077f39g06u/iAG/YPNLB/EJ0eERrWycKtvB0L/bjiS4J5NEU8QeJRp6aTi9IMJfBzvgLfMhg75pvB4jOFi8mL4P/mjKSN0igq05OpZg81TuEV+tIVkusQZ2bMEIyHg38oekpF6mqvgGLNw9E3kcI3l34BQ4CNS0/SSOXkORoemYQKSwdTUDSVp1vFiWowIWQOmA/0/L1I8IebQlr71RnWm/H8XiIU5opbM175n9vvmwQcLXhM6davfUDdKVUopoxA4jFK4lccVqk7mvrTpLZ+eXoa0ODDT6KYr6B+nWTh5/Qhj5ohZ7oy7ZLhvVaqwpx7ptM9r02TvGetsJpE7gqk4RwFElxYd4=
  on:
    tags: true
    repo: jimzhan/create-esnext-app
dd:
  secure: kFtAzjWyit/PQ2BINvWaM+oSpyuSaN5tjO/sqyn5IWexgRkvfFAq+3YrPlAvSGQK81NqKYwoGNwKnpSxf98fkU73fn6iZC0KsBEa13aQt8xFTkHgpv7MNYq3H2btra1wyhIwMEMDkYIzXKg49NoLSKo1NI6MC+x8lAg6jL0k09vF0f+6ij+V9bFJhnzTW7lDWAZL0aiR6fJ7f1PxxT8xzUbyNEXh2tOcw4M9o0V2GgWCbnG8Mpkow13yl4WVXt/9yOtckbQ1TbgzcEuQkUobPG5YTEN+sw3+MlUsvtAepoBEoGm4xleCrIseN2l7bTDA60F7placx72jXXWVv1K2Bbn5fZJv6OlUYEstn5LoJPqW7T6TS/kytwWUSCvIbzbkZXg9JKfPPl8N8Fx2r0uKncouX+wtdgJZiYBvn15vf7eSXmiJ+ZYha+F97QZqOq3EsnM0DDn8b7fyonG9cFwbSAl/I1nQcwBeK6PI8aBAeHe5dSQFqqgveSOQ/fsC/GC2km7IXfoBwbS8ofIWGzz8/RRLpvuvzkk2WshDcL8KzIfi0h6AWJhYeDrrib6+4eFtrqPzS+lf7XPHSvRcke1J22syF5mSahTrWxBew+jfI+QU3BXPKH0BdsQf4axroHfAqDjqztzVBZswxBTYWiqioHhkPffGC+s4oPxmOkfv2wU=
