language: node_js
node_js:
- '9'
- stable
before_script:
- git config --global user.email "jim.zhan@me.com"
- git config --global user.name "jimzhan"
- git remote rm origin
- git remote add origin https://github.com/jimzhan/create-esnext-app.git
- npm install --global standard-version
after_success:
- npm run release
- npm publish --verbose